name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: Pint

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - uses: actions/cache@v3.0.4
        name: Cache dependencies
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('composer.json') }}

      - name: Prepare the project
        run: |
          cp .env.example .env

      - name: Install dependencies
        run: |
          composer config --global --auth http-basic.renoki-co.repo.repman.io token ${{ secrets.REPMAN_TOKEN }}
          composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Test
        run: |
          vendor/bin/pint --test
